import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import "./css/style.css";
import "./css/plugins.css";
import Head from "next/head";
import SearchBar from "@/components/Layout/SearchBar";
import LeftPanel from "@/components/Layout/LeftPanel";
import Content from "@/components/Utility/COntent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <script src="/js/jquery.js" type="text/javascript" />
        <script src="/js/plugins.js" type="text/javascript" />
        <script src="/js/init.js" type="text/javascript" />
      </Head>

      <body>
        <div className="techwave_fn_fixedsub">
          <ul></ul>
        </div>
        <SearchBar />
        <Header />
        <LeftPanel />
        <div className="techwave_fn_wrapper">
          <div className="techwave_fn_wrap">
            {/* {children} */}
            <Content/>
            </div>
        </div>
        {/* <script type="text/javascript" src="./js/jquery.js"></script>
        <script type="text/javascript" src="./js/plugins.js"></script>
        <script type="text/javascript" src="./js/ie8.js"></script>
        <script type="text/javascript" src="./js/init.js"></script> */}
      </body>
    </html>
  );
}
