import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import "./css/style.css";
import "./css/plugins.css";
import Head from "next/head";
import SearchBar from "@/components/Layout/SearchBar";
import LeftPanel from "@/components/Layout/LeftPanel";
import Content from "@/components/Utility/Content";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" id="html">
      <Head>
        <title>Create Next App</title>
       
      </Head>

      <body>
        <div className="techwave_fn_fixedsub">
          <ul></ul>
        </div>
        <SearchBar />
        <Header />
        <LeftPanel />
        <div className="techwave_fn_wrapper">
          <div className="techwave_fn_wrap">
            {children}
            {/* <Content/> */}
            </div>
        </div>
        <Script src="/js/jquery.js" type="text/javascript" />
        <Script src="/js/plugins.js" type="text/javascript" />
        <Script src="/js/init.js" type="text/javascript" />
      </body>
    </html>
  );
}
